import pg, { Pool, type PoolClient } from 'pg';

/**
 * bigint dan numeric dikembalikan Postgres sebagai string, bukan angka.
 *
 * Alasannya benar: keduanya menampung nilai di luar jangkauan aman angka
 * JavaScript. Tetapi seluruh nilai uang sistem ini berada jauh di bawah batas
 * itu — omzet setahun sembilan miliar rupiah, sementara batas aman JavaScript
 * sembilan ribu triliun — sedangkan dibiarkan sebagai string, harga produk
 * sampai ke form pesanan sebagai teks dan perkaliannya menghasilkan omong
 * kosong tanpa satu pun galat muncul.
 */
pg.types.setTypeParser(pg.types.builtins.INT8, (v) => Number(v));
pg.types.setTypeParser(pg.types.builtins.NUMERIC, (v) => Number(v));

/**
 * Lapisan database.
 *
 * Postgres, bukan SQLite: berkas basis data tidak bertahan di lingkungan
 * serverless, dan modul native better-sqlite3 tidak bisa dipasang di sana.
 *
 * Nilai uang memakai bigint, bukan integer. Omzet setahun usaha ini sudah
 * menyentuh sembilan miliar rupiah, sementara integer Postgres berhenti di
 * 2,1 miliar. SQLite tidak memunculkan masalah ini karena INTEGER-nya 64 bit;
 * pindah ke Postgres dengan integer akan membuat angka meluber tanpa peringatan.
 */
const URL_DB = process.env.DATABASE_URL;
if (!URL_DB) {
  throw new Error('DATABASE_URL belum diisi di .env. Salin dari .env.example lalu sesuaikan.');
}

/* Zona waktu dipasang di setiap koneksi, bukan diandalkan dari setelan server.
   Vercel dan Supabase berjalan di UTC; seluruh laporan sistem ini berkunci pada
   tanggal lokal. Tanpa baris ini, pesanan pukul enam pagi WIB tercatat sebagai
   hari sebelumnya dan rekap harian salah tanpa ada yang menyadarinya. */
export const ZONA = process.env.ZONA_WAKTU ?? 'Asia/Jakarta';

export const pool = new Pool({
  connectionString: URL_DB,
  /* Zona dikirim sebagai parameter startup koneksi, bukan lewat event 'connect'.
     Handler event tidak ditunggu oleh pool, sehingga kueri pertama bisa berjalan
     sebelum SET TIME ZONE selesai — dan justru kueri pertama itulah yang paling
     sering menghitung tanggal. */
  options: `-c timezone=${process.env.ZONA_WAKTU ?? 'Asia/Jakarta'}`,
  /* Lingkungan serverless membuat banyak koneksi berumur pendek; batas kecil
     mencegah satu penyebaran menghabiskan jatah koneksi Postgres. */
  max: Number(process.env.DB_MAKS_KONEKSI ?? 8),
  idleTimeoutMillis: 20_000,
  connectionTimeoutMillis: 10_000,
  ...(process.env.DB_SSL === 'true' ? { ssl: { rejectUnauthorized: false } } : {}),
});

/** Antarmuka kueri yang sama untuk pool maupun klien di dalam transaksi. */
export interface Kueri {
  satu<T>(sql: string, params?: unknown[]): Promise<T | undefined>;
  banyak<T>(sql: string, params?: unknown[]): Promise<T[]>;
  jalankan(sql: string, params?: unknown[]): Promise<number>;
}

function bungkus(p: Pool | PoolClient): Kueri {
  return {
    async satu<T>(sql: string, params: unknown[] = []) {
      const r = await p.query(sql, params as never[]);
      return r.rows[0] as T | undefined;
    },
    async banyak<T>(sql: string, params: unknown[] = []) {
      const r = await p.query(sql, params as never[]);
      return r.rows as T[];
    },
    async jalankan(sql: string, params: unknown[] = []) {
      const r = await p.query(sql, params as never[]);
      return r.rowCount ?? 0;
    },
  };
}

export const db: Kueri = bungkus(pool);

/**
 * Menjalankan beberapa perintah sebagai satu transaksi.
 *
 * Seluruh perintah di dalamnya wajib memakai klien yang diberikan, bukan `db`.
 * Memakai `db` di dalam blok ini mengambil koneksi lain dari pool, sehingga
 * perintahnya berada di luar transaksi dan tidak ikut dibatalkan saat gagal —
 * persis keadaan yang ingin dicegah ketika stok dan pesanan harus berhasil
 * atau gagal bersama-sama.
 */
export async function transaksi<T>(fn: (k: Kueri) => Promise<T>): Promise<T> {
  const klien = await pool.connect();
  try {
    await klien.query('BEGIN');
    const hasil = await fn(bungkus(klien));
    await klien.query('COMMIT');
    return hasil;
  } catch (e) {
    await klien.query('ROLLBACK');
    throw e;
  } finally {
    klien.release();
  }
}

/**
 * Skema.
 *
 * Urutan tabel mengikuti ketergantungan kunci asing: Postgres menolak acuan ke
 * tabel yang belum ada, tidak seperti SQLite yang membiarkannya.
 */
export async function initDb() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS kategori (
      id    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nama  text NOT NULL UNIQUE
    );

    CREATE TABLE IF NOT EXISTS supplier (
      id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nama            text NOT NULL,
      alamat          text,
      kontak          text,
      no_hp           text,
      lead_time_hari  integer NOT NULL DEFAULT 3,
      aktif           boolean NOT NULL DEFAULT true
    );

    CREATE TABLE IF NOT EXISTS karyawan (
      id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nama              text NOT NULL,
      jabatan           text NOT NULL,
      no_hp             text,
      status            text NOT NULL DEFAULT 'aktif' CHECK (status IN ('aktif','cuti','nonaktif')),
      tanggal_bergabung date,
      area_kerja        text,
      foto_url          text
    );

    CREATE TABLE IF NOT EXISTS customer (
      id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      kode          text UNIQUE,
      nama          text NOT NULL,
      alamat        text,
      no_hp         text,
      tipe          text NOT NULL DEFAULT 'toko' CHECK (tipe IN ('toko','grosir','retail','horeka')),
      sales_id      integer REFERENCES karyawan(id),
      limit_kredit  bigint NOT NULL DEFAULT 0,
      status        text NOT NULL DEFAULT 'aktif' CHECK (status IN ('aktif','nonaktif','blokir')),
      lat           double precision,
      lng           double precision,
      dibuat_pada   timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS produk (
      id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      sku            text NOT NULL UNIQUE,
      nama           text NOT NULL,
      kategori_id    integer REFERENCES kategori(id),
      supplier_id    integer REFERENCES supplier(id),
      satuan         text NOT NULL DEFAULT 'pcs',
      harga_beli     bigint NOT NULL DEFAULT 0,
      harga_jual     bigint NOT NULL DEFAULT 0,
      stok           integer NOT NULL DEFAULT 0,
      stok_minimum   integer NOT NULL DEFAULT 0,
      safety_stock   integer NOT NULL DEFAULT 0,
      kelipatan_beli integer NOT NULL DEFAULT 1,
      foto_url       text,
      aktif          boolean NOT NULL DEFAULT true,
      dibuat_pada    timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS pengguna (
      id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username      text NOT NULL UNIQUE,
      nama          text NOT NULL,
      email         text,
      no_hp         text,
      kata_sandi    text NOT NULL,
      peran         text NOT NULL CHECK (peran IN ('owner','admin','gudang','sales','driver','buyer')),
      karyawan_id   integer REFERENCES karyawan(id),
      customer_id   integer REFERENCES customer(id),
      aktif         boolean NOT NULL DEFAULT true,
      dibuat_pada   timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS pesanan (
      id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nomor         text NOT NULL UNIQUE,
      customer_id   integer NOT NULL REFERENCES customer(id),
      sales_id      integer REFERENCES karyawan(id),
      tanggal       date NOT NULL,
      subtotal      bigint NOT NULL DEFAULT 0,
      diskon        bigint NOT NULL DEFAULT 0,
      ongkir        bigint NOT NULL DEFAULT 0,
      total         bigint NOT NULL DEFAULT 0,
      hpp_total     bigint NOT NULL DEFAULT 0,
      status_bayar  text NOT NULL DEFAULT 'belum' CHECK (status_bayar IN ('belum','sebagian','lunas')),
      status_kirim  text NOT NULL DEFAULT 'baru' CHECK (status_kirim IN ('baru','diproses','dikirim','selesai','batal')),
      catatan       text,
      dibuat_oleh   integer REFERENCES pengguna(id),
      dibuat_pada   timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS pesanan_item (
      id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      pesanan_id  integer NOT NULL REFERENCES pesanan(id) ON DELETE CASCADE,
      produk_id   integer NOT NULL REFERENCES produk(id),
      qty         integer NOT NULL,
      harga       bigint NOT NULL,
      harga_beli  bigint NOT NULL DEFAULT 0,
      subtotal    bigint NOT NULL
    );

    CREATE TABLE IF NOT EXISTS pembelian (
      id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nomor         text NOT NULL UNIQUE,
      supplier_id   integer NOT NULL REFERENCES supplier(id),
      tanggal       date NOT NULL,
      total         bigint NOT NULL DEFAULT 0,
      status        text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','dipesan','diterima','batal')),
      catatan       text,
      dibuat_oleh   integer REFERENCES pengguna(id),
      dibuat_pada   timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS pembelian_item (
      id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      pembelian_id  integer NOT NULL REFERENCES pembelian(id) ON DELETE CASCADE,
      produk_id     integer NOT NULL REFERENCES produk(id),
      qty           integer NOT NULL,
      qty_diterima  integer NOT NULL DEFAULT 0,
      harga         bigint NOT NULL,
      subtotal      bigint NOT NULL
    );

    CREATE TABLE IF NOT EXISTS mutasi_stok (
      id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      produk_id     integer NOT NULL REFERENCES produk(id),
      tipe          text NOT NULL CHECK (tipe IN ('masuk','keluar','adjustment')),
      qty           integer NOT NULL,
      stok_sebelum  integer NOT NULL,
      stok_sesudah  integer NOT NULL,
      ref_tipe      text,
      ref_id        integer,
      catatan       text,
      oleh          integer REFERENCES pengguna(id),
      waktu         timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS pengiriman (
      id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nomor         text NOT NULL UNIQUE,
      pesanan_id    integer NOT NULL REFERENCES pesanan(id),
      driver_id     integer REFERENCES karyawan(id),
      status        text NOT NULL DEFAULT 'ditugaskan'
                    CHECK (status IN ('ditugaskan','berangkat','sampai','bongkar','diterima','selesai','gagal')),
      dimulai_pada  timestamptz,
      selesai_pada  timestamptz,
      penerima      text,
      foto_url      text,
      ttd_url       text,
      lat           double precision,
      lng           double precision,
      catatan       text,
      dibuat_pada   timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS aktivitas (
      id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      karyawan_id   integer NOT NULL REFERENCES karyawan(id),
      jenis         text NOT NULL,
      waktu         timestamptz NOT NULL DEFAULT now(),
      lat           double precision,
      lng           double precision,
      foto_url      text,
      pesanan_id    integer REFERENCES pesanan(id),
      pengiriman_id integer REFERENCES pengiriman(id),
      catatan       text
    );

    CREATE TABLE IF NOT EXISTS absensi (
      id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      karyawan_id    integer NOT NULL REFERENCES karyawan(id),
      tanggal        date NOT NULL,
      jam_masuk      time,
      lat_masuk      double precision,
      lng_masuk      double precision,
      foto_masuk     text,
      jarak_masuk_m  integer,
      jam_pulang     time,
      lat_pulang     double precision,
      lng_pulang     double precision,
      foto_pulang    text,
      jarak_pulang_m integer,
      status         text NOT NULL DEFAULT 'hadir' CHECK (status IN ('hadir','terlambat','izin','sakit','alpha')),
      UNIQUE (karyawan_id, tanggal)
    );

    CREATE TABLE IF NOT EXISTS audit_log (
      id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id     integer REFERENCES pengguna(id),
      nama_user   text,
      aksi        text NOT NULL,
      entitas     text NOT NULL,
      entitas_id  integer,
      ringkasan   text,
      nilai_lama  text,
      nilai_baru  text,
      waktu       timestamptz NOT NULL DEFAULT now()
    );

    CREATE TABLE IF NOT EXISTS pengaturan (
      kunci text PRIMARY KEY,
      nilai text NOT NULL
    );

    /* Customer yang mendaftar sendiri lewat APK masuk sebagai 'menunggu' dan
       belum boleh memesan. Distributor mengantar barang ke alamat sungguhan dan
       kerap memberi tempo; siapa pun yang memasang aplikasi tidak boleh langsung
       menjadi pelanggan tanpa ada yang memeriksanya lebih dulu. */
    ALTER TABLE customer DROP CONSTRAINT IF EXISTS customer_status_check;
    ALTER TABLE customer ADD CONSTRAINT customer_status_check
      CHECK (status IN ('menunggu','aktif','nonaktif','blokir'));

    CREATE INDEX IF NOT EXISTS idx_pesanan_tanggal   ON pesanan(tanggal);
    CREATE INDEX IF NOT EXISTS idx_pesanan_customer  ON pesanan(customer_id);
    CREATE INDEX IF NOT EXISTS idx_item_pesanan      ON pesanan_item(pesanan_id);
    CREATE INDEX IF NOT EXISTS idx_item_produk       ON pesanan_item(produk_id);
    CREATE INDEX IF NOT EXISTS idx_mutasi_produk     ON mutasi_stok(produk_id, waktu);
    CREATE INDEX IF NOT EXISTS idx_pembelian_tanggal ON pembelian(tanggal);
    CREATE INDEX IF NOT EXISTS idx_absensi_tanggal   ON absensi(tanggal);
    CREATE INDEX IF NOT EXISTS idx_aktivitas_waktu   ON aktivitas(karyawan_id, waktu);
    CREATE INDEX IF NOT EXISTS idx_audit_waktu       ON audit_log(waktu);
  `);
}

/** Pengaturan disimpan sebagai pasangan kunci-nilai agar owner bisa mengubah
    radius absensi atau hari cakupan kulakan tanpa rilis ulang. */
export async function ambilPengaturan(kunci: string, bawaan: string): Promise<string> {
  const baris = await db.satu<{ nilai: string }>('SELECT nilai FROM pengaturan WHERE kunci = $1', [kunci]);
  return baris?.nilai ?? bawaan;
}

export async function simpanPengaturan(kunci: string, nilai: string, k: Kueri = db) {
  await k.jalankan(
    'INSERT INTO pengaturan (kunci, nilai) VALUES ($1, $2) ON CONFLICT (kunci) DO UPDATE SET nilai = excluded.nilai',
    [kunci, nilai]
  );
}
